volumes:
  db:

services:
  db:
    image: mariadb:10.6
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: nx_rootpassword_db
      MYSQL_PASSWORD: nx_password_db
      MYSQL_DATABASE: nxcloud_db
      MYSQL_USER: nx_user_db

  app:
    image: nextcloud
    depends_on:
      - db
    restart: always
    ports:
      - "8082:80"
    links:
      - db
    environment:
      MYSQL_PASSWORD: nx_password_db
      MYSQL_DATABASE: nxcloud_db
      MYSQL_USER: nx_user_db
      MYSQL_HOST: db

  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - db
    restart: always
    ports:
      - "8083:80"
    environment:
      PMA_HOST: db
      PMA_USER: nx_user_db
      PMA_PASSWORD: nx_password_db